apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.1.2
    helm:
      releaseName: postgresql
      values: |
        auth:
          postgresPassword: airflow-postgres
          username: airflow
          password: airflow-password
        persistence:
          enabled: true
          size: 20Gi
          storageClass: local-path
        primary:
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
        readReplicas:
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

